# Generated by Django 5.2.4 on 2025-07-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='source_destination',
            new_name='source_or_destination',
        ),
    ]
