# Generated by Django 5.2.4 on 2025-07-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_logs', '0003_account_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDocument',
        ),
    ]
