# Generated by Django 5.2.4 on 2025-07-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_logs', '0004_delete_accountdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('BDT', 'Taka (BDT)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Pound Sterling (GBP)'), ('OTHER', 'Other')], default='BDT', max_length=5),
        ),
    ]
