name: Build and Deploy to Render

on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/account-tracker:latest

      - name: Trigger Render deploy hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
